[Service]
Host = "edgex-device-modbus"
Port = 49991
ConnectRetries = 3
Labels = []
OpenMsg = "device modbus started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = true
File = "./device-Modbus.log"

[Writable]
LogLevel = "INFO"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "/custom-config"

# Pre-define Devices
[[DeviceList]]
  Name = "WISE-4012"
  Profile = "WISE-4012"
  Description = "WISE-4012"
  labels = [ "modbus TCP" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.modbus-tcp]
       Address = "172.17.0.1"
       Port = "502"
       UnitID = "1"
  [[DeviceList.AutoEvents]]
    Frequency = "3s"
    OnChange = false
    Resource = "Temperature"
  [[DeviceList.AutoEvents]]
    Frequency = "3s"
    OnChange = false
    Resource = "WaterLevel"
[[DeviceList]]
  Name = "FATEKPLC"
  Profile = "FATEKPLC"
  Description = "FATEKPLC"
  labels = [ "modbus RTU" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.modbus-rtu]
       Address = "/dev/ttyS0"
       BaudRate = "9600"
       DataBits = "8"
       StopBits = "1"
       Parity = "E"
       UnitID = "1"
  [[DeviceList.AutoEvents]]
    Frequency = "3s"
    OnChange = false
    Resource = "Pump"
